packages:
  - packages/context
  - packages/core
  - packages/decorator-barebones
  - packages/decorator-mantine
  - packages/decorator-mui
  - packages/hooks

linkWorkspacePackages: true

publicHoistPattern:
  - "*react*"
  - "*zustand*"

shamefullyHoist: true
autoInstallPeers: true

overrides:
  react: "19.2.5"
  react-dom: "19.2.5"
  zustand: "5.0.12"
